name: PR Build

on:
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.15.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install 
      run: |
        npm ci
    - name: Build
      run: | 
        npm run build
    - name: Test
      run: | 
        npm test
      env:
        CI: true
